### Homework 3 Numpy Arrays and Pandas

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into a numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [10]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. (2 pts) What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [11]:
car_dtype = car.dtype
mpg_dtype = mpg.dtype
horsepower_dtype = horsepower.dtype
origin_dtype = origin.dtype

print("Data type of 'car' array:", car_dtype)
print("Data type of 'mpg' array:", mpg_dtype)
print("Data type of 'horsepower' array:", horsepower_dtype)
print("Data type of 'origin' array:", origin_dtype)

Data type of 'car' array: object
Data type of 'mpg' array: float64
Data type of 'horsepower' array: float64
Data type of 'origin' array: object


2. (1 pt) `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#This action is called aliasing. It allows you to call out a function without writing the full term. It also allows for better readability. 

3. (2 pts) Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [16]:
car_ndim = car.ndim
mpg_ndim = mpg.ndim
cylinders_ndim = cylinders.ndim
displacement_ndim = displacement.ndim
horsepower_ndim = horsepower.ndim
weight_ndim = weight.ndim
acceleration_ndim = acceleration.ndim
model_ndim = model.ndim
origin_ndim = origin.ndim

print("Number of dimensions for 'car' array:", car_ndim)
print("Number of dimensions for 'mpg' array:", mpg_ndim)
print("Number of dimensions for 'cylinders' array:", cylinders_ndim)
print("Number of dimensions for 'horsepower' array:", horsepower_ndim)
print("Number of dimensions for 'weight' array:", weight_ndim)
print("Number of dimensions for 'acceleration' array:", acceleration_ndim)
print("Number of dimesions for 'model' array:", model_ndim)
print("Number of dimensions for origin' array:", origin_ndim)

Number of dimensions for 'car' array: 1
Number of dimensions for 'mpg' array: 1
Number of dimensions for 'cylinders' array: 1
Number of dimensions for 'horsepower' array: 1
Number of dimensions for 'weight' array: 1
Number of dimensions for 'acceleration' array: 1
Number of dimesions for 'model' array: 1
Number of dimensions for origin' array: 1


4. (3 pts) What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help) (1 pt extra credit)

In [20]:
import numpy as np

horsepower_sum = np.sum(horsepower)

horsepower_min = np.min(horsepower)

horsepower_max = np.max(horsepower)

horsepower_median = np.median(horsepower)
import statistics as st
horsepower_mode = st.mode(horsepower)

print("Sum of 'horsepower':", horsepower_sum)
print("Minimum 'horsepower':", horsepower_min)
print("Maximum 'horsepower':", horsepower_max)
print("Median 'horsepower':", horsepower_median) 
print("Mode 'horsepower':", horsepower_mode)

Sum of 'horsepower': 42033.0
Minimum 'horsepower': 0.0
Maximum 'horsepower': 230.0
Median 'horsepower': 93.5
Mode 'horsepower': 150.0


5. (2 pts) Select the last element in each subarray (do this with one operation.)

In [21]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [15]:
import numpy as np

select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
last_elements = select_more [:, -1]

print(last_elements)

[3 6 9]


6. (2 pts) Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [21]:
np.lookfor('log')
a = np.array(np.log10(mpg))
a

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

/var/folders/19/_33mhsx56q96g7nyjyp76kyc0000gn/T/ipykernel_89010/3186263438.py:2: RuntimeWarning: divide by zero encountered in log10
  a = np.array(np.log10(mpg))


array([1.25527251, 1.17609126, 1.25527251, 1.20411998, 1.23044892,
       1.17609126, 1.14612804, 1.14612804, 1.14612804, 1.17609126,
             -inf,       -inf,       -inf,       -inf,       -inf,
       1.17609126, 1.14612804,       -inf, 1.17609126, 1.14612804,
       1.38021124, 1.34242268, 1.25527251, 1.32221929, 1.43136376,
       1.41497335, 1.39794001, 1.38021124, 1.39794001, 1.41497335,
       1.32221929, 1.        , 1.        , 1.04139269, 0.95424251,
       1.43136376, 1.44715803, 1.39794001, 1.39794001,       -inf,
       1.2787536 , 1.20411998, 1.23044892, 1.2787536 , 1.25527251,
       1.14612804, 1.14612804, 1.14612804, 1.14612804, 1.07918125,
       1.11394335, 1.11394335, 1.25527251, 1.34242268, 1.2787536 ,
       1.25527251, 1.36172784, 1.44715803, 1.47712125, 1.47712125,
       1.49136169, 1.54406804, 1.43136376, 1.41497335, 1.38021124,
       1.39794001, 1.36172784, 1.30103   , 1.32221929, 1.11394335,
       1.14612804, 1.17609126, 1.14612804, 1.23044892, 1.04139

7. (2 pts) Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [22]:
bool_arr = np.array(origin=='US')
print(bool_arr)

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

8. (2 pts) Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [23]:
print(car[bool_arr[:]])

['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Chevrolet Chevelle Concours (sw)' 'Ford Torino (sw)'
 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)' 'Dodge Challenger SE'
 "Plymouth 'Cuda 340" 'Ford Mustang Boss 302' 'Chevrolet Monte Carlo'
 'Buick Estate Wagon (sw)' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200' 'Hi 1200D'
 'Chevrolet Vega 2300' 'Ford Pinto' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Country Squire (sw)' 'Pontiac Safari (sw)'
 'AMC Hornet Sportabout (sw)' 'Chevrolet Vega (sw)' 'Pontiac Firebird'
 'Ford Mustang' 'Mercury Capri 2000' 'Plymouth Cricket'
 'Dodge Colt Hardtop' 'Chevrolet Vega' 'Ford

### Use numpy or pandas to answer the following questions.

9. (3 pts) What is the average horsepower for `Europe` cars? (Hint: create a boolean index of 'US' apply it to horsepower and perform the calculation.)

In [25]:
bool= np.array(origin=='Europe')
Average = np.mean(horsepower[bool[:]])
print(Average)

78.78082191780823


10. (3 pts) On average are Japanese cars more fuel-efficient than US cars? Show the code that you used to determine this.  

In [27]:
Japanese= np.array(origin=='Japan')
J_eff = np.mean(mpg[Japanese[:]])
US_cars = np.array(origin=='US')
US_eff = np.mean(mpg[US_cars[:]])
if J_eff> US_eff:
    print('Japanese cars are more fuel-efficent')
else:
    print('US cars are more fuel-efficient')

Japanese cars are more fuel-efficent


11. (3 pts) What is the correlation coefficient of `mpg` and `weight`? What is a correlation coefficient? What does the result indicate about the relationship between mpg and weight? 

In [28]:
df = pd.read_csv('cars.csv',delimiter=';')
np.corrcoef(df['MPG'], df['Weight']) 

array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])

Extra credit: (3 pts) Create a new pandas dataframe that has the average mpg, weight, and horsepower per country of origin